import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import * as url from 'url';
const __filename = url.fileURLToPath(import.meta.url);
const __dirname = url.fileURLToPath(new URL('.', import.meta.url));

let settings: Settings;
const settingsFile = join(__dirname, '../../../serials.json');
try {
  settings = JSON.parse(readFileSync(settingsFile).toString('utf8'));
} catch (e) {
  console.error(e);
}

export const getSettings = () => settings;

export const updateSettings = (update) => {
  settings = { ...settings, ...update };
  writeFileSync(settingsFile, JSON.stringify(settings));
};

// Generated by https://quicktype.io

export interface Settings {
  tradfri: Tradfri;
  deconz: Deconz;
}

export interface Deconz {
  name: string;
  password: string;
  apiKey?: string;
}

export interface Tradfri {
  id: string;
  securityCode: string;
  serial: string;
  identity: string;
  psk: string;
}
