import { i3, Node, Workspace } from './utils/i3.js';

export type I3Tree = Node;
export type Command = `${AvailableI3Commands} ${string}`;

export function i3Command(arg: Command): Promise<boolean> {
  return new Promise<boolean>((resolve, reject) => {
    i3.command(
      arg as string,
      (err, result: { success: boolean; error?: string; parse_error?: boolean }[]) => {
        if (err) {
          return reject(err);
        }
        const parseError = result.some((r) => r.parse_error);
        if (result.some((r) => r.error)) {
          const errorStr = result.map((r) => r.error).join(', ');
          return reject(parseError ? 'Error parsing command: ' + errorStr : errorStr);
        }
        resolve(result.every((r) => r.success));
      },
    );
  });
}
export interface Outputs {
  left: string;
  middle: string;
  right: string;
  rest: string[];
}

function _i3Outputs(): Promise<Outputs> {
  return new Promise((resolve, reject) => {
    i3.outputs((err, d) => {
      if (err) {
        console.log('i3Outputs error', err);
        return reject(err);
      }
      try {
        const displays = d
          /** get the active ones */
          .filter((r) => r.active)
          /** sort on left to right order */
          .sort((x, y) => (x.rect.x < y.rect.x ? -1 : 1))
          /** extract only the names */
          .map((r) => {
            return r.name;
          });
        const [left, middle, right, ...rest] = displays;
        resolve({ left, middle, right, rest });
      } catch (e) {
        console.log('i3Outputs catch error', e);
        return reject(e);
      }
    });
  });
}

export const i3Outputs = _i3Outputs();

export function i3WorksSpaces(): Promise<Workspace[]> {
  return new Promise((resolve, reject) => {
    i3.workspaces((err, result) => {
      if (err) {
        return reject(err);
      }
      resolve(result);
    });
  });
}
export function i3Tree(): Promise<Node> {
  return new Promise((resolve, reject) => {
    i3.tree((err, result) => {
      if (err) {
        return reject(err);
      }
      resolve(result);
    });
  });
}

export async function moveWP(num: number, mon: keyof Outputs) {
  const display = (await i3Outputs)[mon];
  await i3Command(`workspace number ${num} `);
  return await i3Command(`move workspace to output "${display}"`);
}

export async function focusWP(num: number, mon: keyof Outputs) {
  await moveWP(num, mon);
  const workspaces = await i3WorksSpaces();
  const { output } = workspaces.find((ws) => ws.num === num)??{};
  return await i3Command(`focus output ${output}`);
}

export enum Name {
  DisplayPort0 = 'DisplayPort-0',
  // DisplayPort1 = 'DisplayPort-1',
  DisplayPort2 = 'DisplayPort-2',
  HDMI0 = 'HDMI-A-0',
}

/**
 * this list is used to check if the command is valid
 * @see https://i3wm.org/docs/userguide.html#_command_reference
 */
type AvailableI3Commands =
  | 'move'
  | 'exec'
  | 'exit'
  | 'restart'
  | 'reload'
  | 'shmlog'
  | 'debuglog'
  | 'border'
  | 'layout'
  | 'append_layout'
  | 'workspace'
  | 'focus'
  | 'kill'
  | 'open'
  | 'fullscreen'
  | 'sticky'
  | 'split'
  | 'floating'
  | 'mark'
  | 'unmark'
  | 'resize'
  | 'rename'
  | 'nop'
  | 'scratchpad'
  | 'swap'
  | 'title_format'
  | 'title_window_icon'
  | 'mode'
  | 'bar'
  | 'gaps';

/* the list is generated by running the following command
 * ```bash
 *  i3-msg blah  # this will error out, and print a list of commands
 * ```
 */
